name: "tag"
on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure committer
        run: |
          - git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          - git config user.name "github-actions[bot]"
      - name: Bump version
        run: |
          - yarn install
          - yarn bumpVersion:master
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true